name: Build Duas App
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Test,Build and Release web app
    env:
      my_secret: ${{secrets.TOKEN}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter test  
      - run: flutter build web --release
